version: '3.8'

services:
  specshield-app:
    build: .
    ports:
      - "9000:9000"
    depends_on:
      mongodb:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      SPRING_DATA_MONGODB_HOST: "specshield-mongodb"
      SPRING_DATA_MONGODB_PORT: "27017"
      SPRING_DATA_MONGODB_DATABASE: "specshield"
      KAFKA_BOOTSTRAP_SERVERS: "specshield-kafka:9092"
    networks:
      - specshield-network

  mongodb:
    image: mongo:7.0
    container_name: specshield-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=specshield
    volumes:
      - mongodb_data:/data/db
    networks:
      - specshield-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  kafka:
    image: apache/kafka:latest
    container_name: specshield-kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://specshield-kafka:9092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

      # KRaft quorum
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"

      # Storage directory
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"

      # Increase payload support (matching your earlier Bitnami config)
      KAFKA_MESSAGE_MAX_BYTES: "524288000"
      KAFKA_SOCKET_REQUEST_MAX_BYTES: "524288000"
      KAFKA_RECEIVE_BUFFER_BYTES: "524288000"
      KAFKA_SEND_BUFFER_BYTES: "524288000"
      KAFKA_MAX_REQUEST_SIZE: "524288000"
      KAFKA_REPLICA_FETCH_MAX_BYTES: "524288000"
      KAFKA_FETCH_MESSAGE_MAX_BYTES: "524288000"
    healthcheck:
      test: [ "CMD", "bash", "-c", "echo >/dev/tcp/localhost/9092" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - specshield-network

volumes:
  mongodb_data:

networks:
  specshield-network:
    driver: bridge